using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace RC.Core.Services
{
    public sealed class AutoPilotRecordsService
    {
        private Type _objecttype;
        private int _numberofinstances;
        private Dictionary<string, int> _maximumoutputs;
        private bool _isgenerateEmail;
        private bool _isgenerateFirstname;
        private bool _isgenerateMiddlename;
        private bool _isgenerateLastName;
        private bool _isgenerateUsername;
        private bool _isgenerateMobileno;

        private DateTime _bdateStartRange;
        private DateTime _bdateEndRange;
        private int _intAgeStartRange;
        private int _intAgeEndRange;

        private string _propertyName_Email;
        private string _propertyName_Firstname;
        private string _propertyName_Middlename;
        private string _propertyName_Lastname;
        private string _propertyName_Username;
        private string _propertyName_Mobilenumber;

        private Dictionary<string, string> _customDataValueGeneration;
        private Dictionary<string, Object> _defaultValues;
        private Dictionary<string, List<Object>> _randomValueSelections;

        private static AutoPilotRecordsService instance;
        private static readonly Object _lock = new Object();

        private AutoPilotRecordsService()
        {
            this._customDataValueGeneration = new Dictionary<string, string>();
            this._defaultValues = new Dictionary<string, Object>();
        }

        public static AutoPilotRecordsService Instance
        {
            get
            {
                lock (_lock)
                {
                    if (instance == null)
                    {
                        instance = new AutoPilotRecordsService();
                    }

                    instance._customDataValueGeneration = new Dictionary<string, string>();
                    instance._defaultValues = new Dictionary<string, object>();
                    instance._randomValueSelections = new Dictionary<string, List<Object>>();
                    return instance;
                }
            }
        }

        public AutoPilotRecordsService SetObjectType(Type objectType)
        {
            instance._objecttype = objectType;

            return instance;
        }

        public AutoPilotRecordsService SetNoOfRecords(int recordNumber)
        {
            instance._numberofinstances = recordNumber;

            return instance;
        }

        public AutoPilotRecordsService GenerateEmail(string propertyName)
        {
            instance._isgenerateEmail = true;
            instance._propertyName_Email = propertyName;

            if (_customDataValueGeneration.ContainsKey("email"))
            {
                return instance;
            }

            _customDataValueGeneration.Add("email", propertyName);
            return instance;
        }

        public AutoPilotRecordsService GenerateAge(string propertyName, int rangeStart, int rangeEnd)
        {
            instance._intAgeStartRange = rangeStart;
            instance._intAgeEndRange = rangeEnd;

            if (_customDataValueGeneration.ContainsKey("age"))
            {
                return instance;
            }

            _customDataValueGeneration.Add("age", propertyName);
            return instance;
        }

        public AutoPilotRecordsService GenerateUsername(string propertyName)
        {
            instance._isgenerateUsername = true;
            instance._propertyName_Username = propertyName;

            if (_customDataValueGeneration.ContainsKey("username"))
            {
                return instance;
            }

            _customDataValueGeneration.Add("username", propertyName);
            return instance;
        }

        public AutoPilotRecordsService GenerateFirstname(string propertyName)
        {
            instance._isgenerateFirstname = true;
            instance._propertyName_Firstname = propertyName;

            if (instance._customDataValueGeneration.ContainsKey("firstname"))
            {
                return instance;
            }

            instance._customDataValueGeneration.Add("firstname", propertyName);
            return instance;
        }

        public AutoPilotRecordsService GenerateMiddlename(string propertyName)
        {
            instance._isgenerateMiddlename = true;
            instance._propertyName_Middlename = propertyName;

            if (_customDataValueGeneration.ContainsKey("middlename"))
            {
                return instance;
            }

            _customDataValueGeneration.Add("middlename", propertyName);
            return instance;
        }

        public AutoPilotRecordsService GenerateLastname(string propertyName)
        {
            instance._isgenerateLastName = true;
            instance._propertyName_Lastname = propertyName;

            if (_customDataValueGeneration.ContainsKey("lastname"))
            {
                return instance;
            }

            _customDataValueGeneration.Add("lastname", propertyName);
            return instance;
        }

        public AutoPilotRecordsService GenerateMobileNumber(string propertyName)
        {
            instance._isgenerateMobileno = true;
            instance._propertyName_Mobilenumber = propertyName;

            if (_customDataValueGeneration.ContainsKey("mobilenumber"))
            {
                return instance;
            }

            _customDataValueGeneration.Add("mobilenumber", propertyName);
            return instance;
        }

        public AutoPilotRecordsService GenerateBirthdate(string propertyName, DateTime startRange, DateTime endRange)
        {
            instance._bdateStartRange = startRange;
            instance._bdateEndRange = endRange;

            if (_customDataValueGeneration.ContainsKey("birthdate"))
            {
                return instance;
            }

            _customDataValueGeneration.Add("birthdate", propertyName);
            return instance;
        }

        //public AutoPilotRecordsService GenerateGUID(string propertyName)
        //{
        //    instance._propertyName_Mobilenumber = propertyName;

        //    if (_customDataValueGeneration.ContainsKey("mobilenumber"))
        //    {
        //        return instance;
        //    }

        //    _customDataValueGeneration.Add("mobilenumber", propertyName);
        //    return instance;
        //}

        public AutoPilotRecordsService SetDefaultValue(string propertyName, object defaultValue)
        {
            _defaultValues.Add(propertyName, defaultValue);

            return instance;
        }

        public AutoPilotRecordsService GenerateValueFromSelections(string propertyName, List<object> selectionList)
        {
            if (!_randomValueSelections.ContainsKey(propertyName))
            {
                _randomValueSelections.Add(propertyName, selectionList);
            }

            return instance;
        }


        public List<T> AutoPilotNow<T>()
        {
            List<T> _instances = new List<T>();
            PropertyInfo[] properties = this._objecttype.GetProperties();

            for (int i = 1; i <= this._numberofinstances; i++)
            {
                var instance = Activator.CreateInstance(this._objecttype);

                foreach (PropertyInfo property in properties)
                {
                    var propertyInfo = instance.GetType().GetProperty(property.Name);

                    if (property.PropertyType == typeof(string))
                    {
                        propertyInfo.SetValue(instance, "This is a random string...", null);


                        if (_customDataValueGeneration.ContainsKey("firstname") && propertyInfo.Name == this._propertyName_Firstname)
                        {
                            propertyInfo.SetValue(instance, GenerateFirstname(), null);
                        }
                        if (_customDataValueGeneration.ContainsKey("lastname") && propertyInfo.Name == this._propertyName_Lastname)
                        {
                            propertyInfo.SetValue(instance, GenerateLastname(), null);
                        }
                        if (_customDataValueGeneration.ContainsKey("username") && propertyInfo.Name == this._propertyName_Username)
                        {
                            propertyInfo.SetValue(instance, GenerateLastname(), null);
                        }
                        if (_customDataValueGeneration.ContainsKey("middlename") && propertyInfo.Name == this._propertyName_Middlename)
                        {
                            propertyInfo.SetValue(instance, GenerateMiddlename(), null);
                        }
                        if (_customDataValueGeneration.ContainsKey("mobilenumber") && propertyInfo.Name == this._propertyName_Mobilenumber)
                        {
                            propertyInfo.SetValue(instance, GetMobileNumber(), null);
                        }
                    }
                    if (property.PropertyType == typeof(int))
                    {
                        propertyInfo.SetValue(instance, 100, null);
                    }
                    if (property.PropertyType == typeof(decimal))
                    {
                        propertyInfo.SetValue(instance, 50.50, null);
                    }
                    if (property.PropertyType == typeof(long))
                    {
                        propertyInfo.SetValue(instance, 06465464, null);

                        if (_customDataValueGeneration.ContainsKey("mobilenumber") && propertyInfo.Name == this._propertyName_Mobilenumber)
                        {
                            propertyInfo.SetValue(instance, GetMobileNumber(), null);
                        }
                    }
                    if (property.PropertyType == typeof(bool))
                    {
                        propertyInfo.SetValue(instance, new Random().Next(1, 2) == 1 ? true : false, null);
                    }
                    if (property.PropertyType == typeof(double))
                    {
                        propertyInfo.SetValue(instance, 1000, null);

                        if (_customDataValueGeneration.ContainsKey("mobilenumber") && propertyInfo.Name == this._propertyName_Mobilenumber)
                        {
                            propertyInfo.SetValue(instance, GetMobileNumber(), null);
                        }
                    }
                    if (property.PropertyType == typeof(DateTime))
                    {
                        propertyInfo.SetValue(instance, GenerateBirthdate(), null);
                    }
                }

                //var propertieslist = this._objecttype.GetProperties().ToList();

                foreach (var item in _defaultValues)
                {
                    PropertyInfo result = properties.Where(x => x.Name == item.Key).Count() > 0 ? properties.Where(x => x.Name == item.Key).First() : null;

                    var propertyInfo = instance.GetType().GetProperty(item.Key);

                    if (result.PropertyType == typeof(string))
                    {
                        propertyInfo.SetValue(instance, (string)item.Value, null);
                    }
                    if (result.PropertyType == typeof(int))
                    {
                        propertyInfo.SetValue(instance, item.Value, null);
                    }
                    if (result.PropertyType == typeof(decimal))
                    {
                        propertyInfo.SetValue(instance, item.Value, null);
                    }
                    if (result.PropertyType == typeof(float))
                    {
                        propertyInfo.SetValue(instance, item.Value, null);
                    }
                    if (result.PropertyType == typeof(long))
                    {
                        propertyInfo.SetValue(instance, item.Value, null);
                    }
                    if (result.PropertyType == typeof(bool))
                    {
                        propertyInfo.SetValue(instance, item.Value, null);
                    }
                    if (result.PropertyType == typeof(double))
                    {
                        propertyInfo.SetValue(instance, double.Parse((string)item.Value), null);
                    }
                    if (result.PropertyType == typeof(DateTime))
                    {
                        propertyInfo.SetValue(instance, item.Value, null);
                    }
                    if (result.PropertyType == typeof(Guid))
                    {
                        propertyInfo.SetValue(instance, item.Value, null);
                    }
                }

                foreach (var item in _randomValueSelections)
                {
                    int selectioncount = item.Value.Count;
                    int selectedrandom = new Random().Next(0, selectioncount);
                    Object selectedvalue = _randomValueSelections[item.Key][selectedrandom];

                    PropertyInfo result = properties.Where(x => x.Name == item.Key).Count() > 0 ? properties.Where(x => x.Name == item.Key).First() : null;

                    var propertyInfo = instance.GetType().GetProperty(item.Key);

                    if (result.PropertyType == typeof(string))
                    {
                        propertyInfo.SetValue(instance, (string)selectedvalue, null);
                    }
                    if (result.PropertyType == typeof(int))
                    {
                        propertyInfo.SetValue(instance, (int)selectedvalue, null);
                    }
                    if (result.PropertyType == typeof(decimal))
                    {
                        propertyInfo.SetValue(instance, (decimal)selectedvalue, null);
                    }
                    if (result.PropertyType == typeof(float))
                    {
                        propertyInfo.SetValue(instance, (float)selectedvalue, null);
                    }
                    if (result.PropertyType == typeof(long))
                    {
                        propertyInfo.SetValue(instance, (long)selectedvalue, null);
                    }
                    if (result.PropertyType == typeof(bool))
                    {
                        propertyInfo.SetValue(instance, (bool)selectedvalue, null);
                    }
                    if (result.PropertyType == typeof(double))
                    {
                        propertyInfo.SetValue(instance, (double)selectedvalue, null);
                    }
                    if (result.PropertyType == typeof(DateTime))
                    {
                        propertyInfo.SetValue(instance, DateTime.Parse((string)selectedvalue), null);
                    }
                }

                _instances.Add((T)instance);
            }

            return _instances;
        }

        private double GetMobileNumber()
        {
            var random = new Random();
            string s = string.Empty;
            for (int i = 0; i < 11; i++)
                s = String.Concat(s, random.Next(0, 9).ToString());
            return double.Parse(s);
        }

        private string GenerateFirstname()
        {
            var firstnames = GetMaleFirstnames();
            firstnames.AddRange(GetFemaleFirstnames());

            int random_index = new Random().Next(0, 999);

            return firstnames[random_index];
        }

        private DateTime GenerateBirthdate()
        {
            var randomTest = new Random();

            TimeSpan timeSpan = this._bdateEndRange - this._bdateStartRange;
            TimeSpan newSpan = new TimeSpan(0, randomTest.Next(0, (int)timeSpan.TotalMinutes), 0);
            DateTime newDate = this._bdateStartRange + newSpan;

            return newDate;
        }

        private string GenerateLastname()
        {
            var lastnames = GetLastnames();

            int random_index = new Random().Next(0, 999);

            return lastnames[random_index];
        }
        private string GenerateMiddlename()
        {
            var lastnames = GetLastnames();

            int random_index = new Random().Next(0, 999);

            return lastnames[random_index];
        }

        private string GenerateUsername()
        {
            var usernames = GetUsernames();

            int random_index = new Random().Next(0, 400);

            return usernames[random_index];
        }

        public List<string> GetMaleFirstnames()
        {
            return new List<string>() {
"Liam" ,"Noah" ,"Oliver" ,"James" ,"Elijah" ,"William" ,"Henry" ,"Lucas" ,"Benjamin" ,"Theodore" ,"Mateo" ,"Levi"
,"Sebastian" ,"Daniel" ,"Jack" ,"Michael" ,"Alexander" ,"Owen" ,"Asher" ,"Samuel" ,"Ethan" ,"Leo" ,"Jackson" ,"Mason"
,"Ezra" ,"John" ,"Hudson" ,"Luca" ,"Aiden" ,"Joseph" ,"David" ,"Jacob" ,"Logan" ,"Luke" ,"Julian" ,"Gabriel" ,"Grayson"
,"Wyatt" ,"Matthew" ,"Maverick" ,"Dylan" ,"Isaac" ,"Elias" ,"Anthony" ,"Thomas" ,"Jayden" ,"Carter" ,"Santiago" ,"Ezekiel"
,"Charles","Josiah","Caleb","Cooper","Lincoln","Miles","Christopher","Nathan","Isaiah","Kai","Joshua","Andrew","Angel","Adrian"
,"Cameron","Nolan","Waylon","Jaxon","Roman","Eli","Wesley","Aaron","Ian","Christian","Ryan","Leonardo","Brooks","Axel","Walker"
,"Jonathan","Easton","Everett","Weston","Bennett","Robert","Jameson","Landon","Silas","Jose"
,"Beau","Micah","Colton","Jordan","Jeremiah","Parker","Greyson","Rowan","Adam","Nicholas","Theo","Xavier"
,"Hunter"
,"Dominic"
,"Jace"
,"Gael"
,"River"
,"Thiago"
,"Kayden"
,"Damian"
,"August"
,"Carson"
,"Austin"
,"Myles"
,"Amir"
,"Declan"
,"Emmett"
,"Ryder"
,"Luka"
,"Connor"
,"Jaxson"
,"Milo"
,"Enzo"
,"Giovanni"
,"Vincent"
,"Diego"
,"Luis" ,"Archer" ,"Harrison" ,"Kingston" ,"Atlas" ,"Jasper" ,"Sawyer" ,"Legend" ,"Lorenzo" ,"Evan" ,"Jonah" ,"Chase" ,"Bryson" ,"Adriel" ,"Nathaniel" ,"Arthur" ,"Juan" ,"George" ,"Cole" ,"Zion" ,"Jason"
,"Ashton" ,"Carlos" ,"Calvin" ,"Brayden" ,"Elliot" ,"Rhett" ,"Emiliano" ,"Ace" ,"Jayce" ,"Graham" ,"Max" ,"Braxton" ,"Leon","Ivan" ,"Hayden" ,"Jude" ,"Malachi" ,"Dean" ,"Tyler" ,"Jesus" ,"Zachary"
,"Kaiden" ,"Elliott" ,"Arlo" ,"Emmanuel" ,"Ayden" ,"Bentley" ,"Maxwell" ,"Amari" ,"Ryker" ,"Finn" ,"Antonio" ,"Charlie" ,"Maddox" ,"Justin" ,"Judah" ,"Kevin" ,"Dawson"
,"Matteo"
,"Miguel"
,"Zayden"
,"Camden"
,"Messiah"
,"Alan"
,"Alex"
,"Nicolas"
,"Felix"
,"Alejandro"
,"Jesse"
,"Beckett"
,"Matias"
,"Tucker"
,"Emilio"
,"Xander"
,"Knox"
,"Oscar"
,"Beckham"
,"Timothy"
,"Abraham"
,"Andres"
,"Gavin"
,"Brody"
,"Barrett"
,"Hayes"
,"Jett"
,"Brandon"
,"Joel"
,"Victor"
,"Peter"
,"Abel"
,"Edward"
,"Karter"
,"Patrick"
,"Richard"
,"Grant"
,"Avery"
,"King"
,"Caden"
,"Adonis"
,"Riley"
,"Tristan"
,"Kyrie"
,"Blake"
,"Eric"
,"Griffin"
,"Malakai"
,"Rafael"
,"Israel"
,"Tate"
,"Lukas"
,"Nico"
,"Marcus"
,"Stetson"
,"Javier"
,"Colt"
,"Omar"
,"Simon"
,"Kash"
,"Remington"
,"Jeremy"
,"Louis"
,"Mark"
,"Lennox"
,"Callum"
,"Kairo"
,"Nash"
,"Kyler"
,"Dallas"
,"Crew"
,"Preston"
,"Paxton"
,"Steven"
,"Zane"
,"Kaleb"
,"Lane"
,"Phoenix"
,"Paul"
,"Cash"
,"Kenneth"
,"Bryce"
,"Ronan"
,"Kaden"
,"Maximiliano"
,"Walter"
,"Maximus"
,"Emerson"
,"Hendrix"
,"Jax"
,"Atticus"
,"Zayn"
,"Tobias"
,"Cohen"
,"Aziel"
,"Kayson"
,"Rory"
,"Brady"
,"Finley"
,"Holden"
,"Jorge"
,"Malcolm"
,"Clayton"
,"Niko"
,"Francisco"
,"Josue"
,"Brian"
,"Bryan"
,"Cade"
,"Colin"
,"Andre"
,"Cayden"
,"Aidan"
,"Muhammad"
,"Derek"
,"Ali"
,"Elian"
,"Bodhi"
,"Cody"
,"Jensen"
,"Damien"
,"Martin"
,"Cairo"
,"Ellis"
,"Khalil"
,"Otto"
,"Zander"
,"Dante"
,"Ismael"
,"Angelo"
,"Brantley"
,"Manuel"
,"Colson"
,"Cruz"
,"Tatum"
,"Jaylen"
,"Jaden"
,"Erick"
,"Cristian"
,"Romeo"
,"Milan"
,"Reid"
,"Cyrus"
,"Leonel"
,"Joaquin"
,"Ari"
,"Odin"
,"Orion"
,"Ezequiel"
,"Gideon"
,"Daxton"
,"Warren"
,"Casey"
,"Anderson"
,"Spencer"
,"Karson"
,"Eduardo"
,"Chance"
,"Fernando"
,"Raymond"
,"Bradley"
,"Cesar"
,"Wade"
,"Prince"
,"Julius"
,"Dakota"
,"Kade"
,"Koa"
,"Raiden"
,"Callan"
,"Hector"
,"Onyx"
,"Remy"
,"Ricardo"
,"Edwin"
,"Stephen"
,"Kane"
,"Saint"
,"Titus"
,"Desmond"
,"Killian"
,"Sullivan"
,"Mario"
,"Jay"
,"Kamari"
,"Luciano"
,"Royal"
,"Zyaire"
,"Marco"
,"Wilder"
,"Russell"
,"Nasir"
,"Rylan"
,"Archie"
,"Jared"
,"Gianni"
,"Kashton"
,"Kobe"
,"Sergio"
,"Travis"
,"Marshall"
,"Iker"
,"Briggs"
,"Gunner"
,"Apollo"
,"Bowen"
,"Baylor"
,"Sage"
,"Tyson"
,"Kyle"
,"Oakley"
,"Malik"
,"Mathias"
,"Sean"
,"Armani"
,"Hugo"
,"Johnny"
,"Sterling"
,"Forrest"
,"Harvey"
,"Banks"
,"Grady"
,"Kameron"
,"Jake"
,"Franklin"
,"Lawson"
,"Tanner"
,"Eden"
,"Jaziel"
,"Pablo"
,"Reed"
,"Pedro"
,"Zayne"
,"Royce"
,"Edgar"
,"Ibrahim"
,"Winston"
,"Ronin"
,"Leonidas"
,"Devin"
,"Damon"
,"Noel"
,"Rhys"
,"Clark"
,"Corbin"
,"Sonny"
,"Colter"
,"Esteban"
,"Erik"
,"Baker"
,"Adan"
,"Dariel"
,"Kylo"
,"Tripp"
,"Caiden"
,"Frank"
,"Solomon"
,"Major"
,"Memphis"
,"Quinn"
,"Dax"
,"Hank"
,"Donovan"
,"Finnegan"
,"Nehemiah"
,"Andy"
,"Camilo"
,"Asa"
,"Jeffrey"
,"Santino"
,"Isaias"
,"Jaiden"
,"Kian"
,"Fabian"
,"Callen"
,"Ruben"
,"Alexis"
,"Emanuel"
,"Francis"
,"Garrett"
,"Kendrick"
,"Matthias"
,"Wells"
,"Augustus"
,"Jasiah"
,"Alijah"
,"Alonzo"
,"Koda"
,"Collin"
,"Ford"
,"Frederick"
,"Jaxton"
,"Kohen"
,"Troy"
,"Kason"
,"Seth"
,"Denver"
,"Kyson"
,"Ares"
,"Raphael"
,"Bodie"
,"Sylas"
,"Uriel"
,"Zaiden"
,"Shiloh"
,"Lewis"
,"Kieran"
,"Marcos"
,"Bo"
,"Shepherd"
,"Philip"
,"Zaire"
,"Gregory"
,"Princeton"
,"Roberto"
,"Leland"
,"Eithan"
,"Moshe"
,"Johnathan"
,"Lucca"
,"Kenzo"
,"Mack"
,"Porter"
,"Kolton"
,"Kaison"
,"Valentino"
,"Saul"
,"Shane"
,"Jamari"
,"Rocco"
,"Kylan"
,"Deacon"
,"Dalton"
,"Moses"
,"Callahan"
,"Tadeo"
,"Makai"
,"Amiri"
,"Rowen"
,"Drew"
,"Jalen"
,"Kylian"
,"Sutton"
,"Dominick"
,"Reece"
,"Rodrigo"
,"Soren"
,"Kasen"
,"Ridge"
,"Zachariah"
,"Jamir"
,"Peyton"
,"Omari"
,"Trevor"
,"Morgan"
,"Izaiah"
,"Alessandro"
,"Kaysen"
,"Enrique"
,"Marcelo"
,"Sincere"
,"Lucian"
,"Leandro"
,"Armando"
,"Braylen"
,"Jayson"
,"Julio"
,"Lawrence"
,"Cassius"
,"Raul"
,"Jase"
,"Mohammad"
,"Zain"
,"Jayceon"
,"Jonas"
,"Ronald"
,"Ayaan"
,"Rio"
,"Allen"
,"Bruce"
,"Mohamed"
,"Dorian"
,"Maximilian"
,"Keegan"
,"Shawn"
,"Yusuf"
,"Pierce"
,"Ariel"
,"Ander"
,"Conor"
,"Conrad"
,"Phillip"
,"Arjun"
,"Roy"
,"Moises"
,"Arturo"
,"Johan"
,"Gerardo"
,"Atreus"
,"Nikolai"
,"Braylon"
,"Samson"
,"Hezekiah"
,"Kayce"
,"Scott"
,"Gunnar"
,"Jamison"
,"Samir"
,"Keanu"
,"Ledger"
,"Jaime"
,"Finnley"
,"Cannon"
,"Colby"
,"Nikolas"
,"Emmitt"
,"Kamden"
,"Miller"
,"Boone"
,"Hamza"
,"Ocean"
,"Mac"
,"Anakin"
,"Brixton"
,"Roland"
,"Huxley"
,"Zeke"
,"Danny"
,"Marvin"
,"Otis"
,"Albert"
,"Clay"
,"Emir"
,"Boston"
,"Bruno"
,"Lionel"
,"Ozzy"
,"Taylor"
,"Jamie"
,"Augustine"
,"Chaim"
,"Krew"
,"Rayan"
,"Alden"
,"Bellamy"
,"Amos"
,"Drake"
,"Davis"
,"Dustin"
,"Corey"
,"Ahmad"
,"Conner"
,"Gustavo"
,"Layton"
,"Abram"
,"Axton"
,"Chandler"
,"Azariah"
,"Reese"
,"Benson"
,"Tru"
,"Case"
,"Trey"
,"Mauricio"
,"Westin"
,"Gage"
,"Reign"
,"Creed"
,"Mylo"
,"Dennis"
,"Quentin"
,"Madden"
,"Rome"
,"Julien"
,"Sam"
,"Zaid"
,"Marcel"
,"Maximo"
,"Layne"
,"Ahmed"
,"Kannon"
,"Quincy"
,"Yosef"
,"Aarav"
,"Lennon"
,"Ryland"
,"Skyler"
,"Chris"
,"Eliam"
,"Kareem"
,"Kyree"
,"Dario"
,"Donald"
,"Fletcher"
,"Darius"
,"Duke"
,"Rayden"
,"Salem"
,"Vicente"
,"Vincenzo"
,"Cayson"
,"Eliseo"
,"Issac"
,"Lian"
,"Clyde"
,"Wilson"
,"Santana"
,"Tomas"
,"Dexter"
,"Keith"
,"Houston"
,"Harry"
,"Uriah"
,"Lee"
,"Rex"
,"Tony"
,"Carmelo"
,"Alberto"
,"Loyal"
,"Trace"
,"Alfredo"
,"Riggs"
,"Forest"
,"Raylan"
,"Salvador"
,"Jakari"
,"Zakai"
,"Louie"
,"Flynn"
,"Leonard"
,"Mohammed"
,"Derrick"
,"Musa"
,"Avi"
,"Ty"
,"Westley"
,"Ambrose"
,"Brycen"
,"Aron"
,"Caspian"
,"Gatlin"
,"Harlan"
,"Dillon"
,"Emery"
,"Nixon"
,"Tommy"
,"Watson"
,"Zayd"
,"Azrael"
,"Zyair"
,"Azriel"
,"Legacy"
,"Cillian"
,"Alvin"
,"Bridger"
,"Alec"
,"Edison"
,"Kingsley"
,"Remi"
,"Briar"
,"Jaxxon"
,"Truett"
,"Lachlan"
,"Cal"
,"Landen"
,"Roger"
,"Alonso"
,"Kaiser"
,"Blaze"
,"Jerry"
,"Seven"
,"Kenji"
,"Noe"
,"Quinton"
,"Grey"
,"Jefferson"
,"Marcellus"
,"Ray"
,"Kyro"
,"Benicio"
,"Justice"
,"Neil"
,"Idris"
,"Bear"
,"Kiaan"
,"Wayne"
,"Ben"
,"Junior"
,"Karim"
,"Yehuda"
,"Jimmy"
,"Ramon"
,"Bjorn"
,"Nathanael"
,"Stanley"
,"Hassan"
,"Magnus"
,"Trenton"
,"Brayan"
,"Brock"
,"Jagger"
,"Cason"
,"Dakari"
,"Rey"
,"Abdiel"
,"Abdullah"
,"Casen"
,"Jiraiya"
,"Lance"
,"Misael"
,"Alvaro"
,"Robin"
,"Langston"
,"Nelson"
,"Wes"
,"Khari"
,"Landyn"
,"Jakai"
,"Lochlan" ,"Valentin" ,"Keaton" ,"Amias" ,"Joziah" ,"Thaddeus" ,"Jedidiah" ,"Orlando" ,"Eliel" ,"Hugh" ,"Koen" ,"Calum" ,"Enoch" ,"Mitchell" ,"Rohan" ,"Aryan" ,"Dilan"
,"Aden" ,"Allan" ,"Leighton" ,"Elisha"
,"Evander"
,"Castiel"
,"Curtis"
,"Kellen"
,"Dash"
,"Douglas"
,"Eddie"
,"Melvin"
,"Avyaan"
,"Everest"
,"Zamir"
,"Ricky"
,"Dutton"
,"Yahir"
,"Devon"
,"Franco"
,"Khaza"
,"Dior"
,"Leif"
,"Sevyn"
,"Guillermo"
,"Ira"
,"Emory"
,"Felipe","Titan","Alfred"
,"Azael","Zahir"
,"Kellan"
,"Darren","Rudy"
,"Ayan","Leroy"
,"Anders","Ishaan"
,"Reuben","Boden"
,"Mccoy"
,"Heath","Kase"
,"Wylder"
,"Judson","Khai"
,"Kye","Axl"
,"Crue"
,"Ernesto"
,"Ahmir"
,"Zyon"
,"Aries"
,"Mustafa"
,"Santos"
,"Dane"
,"Damari"
,"Elio"
,"Jadiel"
,"Jovanni"
,"Salvatore"
,"Mathew"
,"Kolson"
,"Nova"
,"Brendan"
,"Murphy"
,"Brodie"
,"Damir"
,"Rocky"
,"Larry"
,"Fisher"
,"Waylen"
,"Byron"
,"Ermias"
,"Joey"
,"Joe"
,"Jon"
,"Arian"
,"Chosen"
,"Jairo"
,"Vihaan"
,"Kylen"
,"Ameer"
,"Dion"
,"Jrue"
,"Kaizen"
,"Yousef"
,"Bryant"
,"Cullen"
,"Kaisen"
,"Kelvin"
,"Zen"
,"Kartier"
,"Randy"
,"Shepard"
,"Alaric"
,"Cain"
,"Jeremias"
,"Alfonso"
,"Brecken"
,"Colten"
,"Gian"
,"Rhodes"
,"Wesson"
,"Duncan"
,"Harold"
,"Henrik"
,"Harley"
,"Alistair"
,"Agustin"
,"Jericho"
,"Talon"
,"Westyn"
,"Cassian"
,"Eugene"
,"Ryatt"
,"Shmuel"
,"Braden"
,"Yahya"
,"Aldo"
,"Dangelo"
,"Ezrah"
,"Korbin"
,"Zavier"
,"Bronson"
,"Teo"
,"Jones"
,"Neo"
,"Stefan"
,"Van"
,"Mekhi"
,"Coleson"
,"Eren"
,"Ignacio"
,"Kristian"
,"Harlem"
,"Zev"
,"Canaan"
,"Cedric"
,"Khalid"
,"Bode"
,"Gary"
,"Rene"
,"Benedict"
,"Maxton"
,"Thatcher"
,"Wallace"
,"Davian"
,"Gordon"
,"Niklaus"
,"Yisroel"
,"Kabir"
,"Osman"
,"Adler"
,"Darian"
,"Terry"
,"Cartier"
,"Osiris"
,"Vance"
,"Demetrius"
,"Kamryn"
,"Lux"
,"Stone"
,"Jaxx"
,"Kooper"
,"Rodney"
,"Aurelio"
,"Darwin"
,"Jakob"
,"Zechariah"
,"Brennan"
,"Marlon"
,"Meir"
,"Yael"
,"Asaiah"
,"Atharv"
,"Imran"
,"Ivaan"
,"Kanan"
,"Kalel"
,"London"
};
        }

        public List<string> GetLastnames()
        {

            return new List<string>(){
"Smith"
,"Johnson"
,"Williams"
,"Brown"
,"Jones"
,"Garcia"
,"Miller"
,"Davis"
,"Rodriguez"
,"Martinez"
,"Hernandez"
,"Lopez"
,"Gonzalez"
,"Wilson"
,"Anderson"
,"Thomas"
,"Taylor"
,"Moore"
,"Jackson"
,"Martin"
,"Lee"
,"Perez"
,"Thompson"
,"White"
,"Harris"
,"Sanchez"
,"Clark"
,"Ramirez"
,"Lewis"
,"Robinson"
,"Walker"
,"Young"
,"Allen"
,"King"
,"Wright"
,"Scott"
,"Torres"
,"Nguyen"
,"Hill"
,"Flores"
,"Green"
,"Adams"
,"Nelson"
,"Baker"
,"Hall"
,"Rivera"
,"Campbell"
,"Mitchell"
,"Carter"
,"Roberts"
,"Gomez"
,"Phillips"
,"Evans"
,"Turner"
,"Diaz"
,"Parker"
,"Cruz"
,"Edwards"
,"Collins"
,"Reyes"
,"Stewart"
,"Morris"
,"Morales"
,"Murphy"
,"Cook"
,"Rogers"
,"Gutierrez"
,"Ortiz"
,"Morgan"
,"Cooper"
,"Peterson"
,"Bailey"
,"Reed"
,"Kelly"
,"Howard"
,"Ramos"
,"Kim"
,"Cox"
,"Ward"
,"Richardson"
,"Watson"
,"Brooks"
,"Chavez"
,"Wood"
,"James"
,"Bennett"
,"Gray"
,"Mendoza"
,"Ruiz"
,"Hughes"
,"Price"
,"Alvarez"
,"Castillo"
,"Sanders"
,"Patel"
,"Myers"
,"Long"
,"Ross"
,"Foster"
,"Jimenez"
,"Powell"
,"Jenkins"
,"Perry"
,"Russell"
,"Sullivan"
,"Bell"
,"Coleman"
,"Butler"
,"Henderson"
,"Barnes"
,"Gonzales"
,"Fisher"
,"Vasquez"
,"Simmons"
,"Romero"
,"Jordan"
,"Patterson"
,"Alexander"
,"Hamilton"
,"Graham"
,"Reynolds"
,"Griffin"
,"Wallace"
,"Moreno"
,"West"
,"Cole"
,"Hayes"
,"Bryant"
,"Herrera"
,"Gibson"
,"Ellis"
,"Tran"
,"Medina"
,"Aguilar"
,"Stevens"
,"Murray"
,"Ford"
,"Castro"
,"Marshall"
,"Owens"
,"Harrison"
,"Fernandez"
,"Mcdonald"
,"Woods"
,"Washington"
,"Kennedy"
,"Wells"
,"Vargas"
,"Henry"
,"Chen"
,"Freeman"
,"Webb"
,"Tucker"
,"Guzman"
,"Burns"
,"Crawford"
,"Olson"
,"Simpson"
,"Porter"
,"Hunter"
,"Gordon"
,"Mendez"
,"Silva"
,"Shaw"
,"Snyder"
,"Mason"
,"Dixon"
,"Munoz"
,"Hunt"
,"Hicks"
,"Holmes"
,"Palmer"
,"Wagner"
,"Black"
,"Robertson"
,"Boyd"
,"Rose"
,"Stone"
,"Salazar"
,"Fox"
,"Warren"
,"Mills"
,"Meyer"
,"Rice"
,"Schmidt"
,"Garza"
,"Daniels"
,"Ferguson"
,"Nichols"
,"Stephens"
,"Soto"
,"Weaver"
,"Ryan"
,"Gardner"
,"Payne"
,"Grant"
,"Dunn"
,"Kelley"
,"Spencer"
,"Hawkins"
,"Arnold"
,"Pierce"
,"Vazquez"
,"Hansen"
,"Peters"
,"Santos"
,"Hart"
,"Bradley"
,"Knight"
,"Elliott"
,"Cunningham"
,"Duncan"
,"Armstrong"
,"Hudson"
,"Carroll"
,"Lane"
,"Riley"
,"Andrews"
,"Alvarado"
,"Ray"
,"Delgado"
,"Berry"
,"Perkins"
,"Hoffman"
,"Johnston"
,"Matthews"
,"Pena"
,"Richards"
,"Contreras"
,"Willis"
,"Carpenter"
,"Lawrence"
,"Sandoval"
,"Guerrero"
,"George"
,"Chapman"
,"Rios"
,"Estrada"
,"Ortega"
,"Watkins"
,"Greene"
,"Nunez"
,"Wheeler"
,"Valdez"
,"Harper"
,"Burke"
,"Larson"
,"Santiago"
,"Maldonado"
,"Morrison"
,"Franklin"
,"Carlson"
,"Austin"
,"Dominguez"
,"Carr"
,"Lawson"
,"Jacobs"
,"Obrien"
,"Lynch"
,"Singh"
,"Vega"
,"Bishop"
,"Montgomery"
,"Oliver"
,"Jensen"
,"Harvey"
,"Williamson"
,"Gilbert"
,"Dean"
,"Sims"
,"Espinoza"
,"Howell"
,"Li"
,"Wong"
,"Reid"
,"Hanson"
,"Le"
,"Mccoy"
,"Garrett"
,"Burton"
,"Fuller"
,"Wang"
,"Weber"
,"Welch"
,"Rojas"
,"Lucas"
,"Marquez"
,"Fields"
,"Park"
,"Yang"
,"Little"
,"Banks"
,"Padilla"
,"Day"
,"Walsh"
,"Bowman"
,"Schultz"
,"Luna"
,"Fowler"
,"Mejia"
,"Davidson"
,"Acosta"
,"Brewer"
,"May"
,"Holland"
,"Juarez"
,"Newman"
,"Pearson"
,"Curtis"
,"Cortez"
,"Douglas"
,"Schneider"
,"Joseph"
,"Barrett"
,"Navarro"
,"Figueroa"
,"Keller"
,"Avila"
,"Wade"
,"Molina"
,"Stanley"
,"Hopkins"
,"Campos"
,"Barnett"
,"Bates"
,"Chambers"
,"Caldwell"
,"Beck"
,"Lambert"
,"Miranda"
,"Byrd"
,"Craig"
,"Ayala"
,"Lowe"
,"Frazier"
,"Powers"
,"Neal"
,"Leonard"
,"Gregory"
,"Carrillo"
,"Sutton"
,"Fleming"
,"Rhodes"
,"Shelton"
,"Schwartz"
,"Norris"
,"Jennings"
,"Watts"
,"Duran"
,"Walters"
,"Cohen"
,"Mcdaniel"
,"Moran"
,"Parks"
,"Steele"
,"Vaughn"
,"Becker"
,"Holt"
,"Deleon"
,"Barker"
,"Terry"
,"Hale"
,"Leon"
,"Hail"
,"Benson"
,"Haynes"
,"Horton"
,"Miles"
,"Lyons"
,"Pham"
,"Graves"
,"Bush"
,"Thornton"
,"Wolfe"
,"Warner"
,"Cabrera"
,"Mckinney"
,"Mann"
,"Zimmerman"
,"Dawson"
,"Lara"
,"Fletcher"
,"Page"
,"Mccarthy"
,"Love"
,"Robles"
,"Cervantes"
,"Solis"
,"Erickson"
,"Reeves"
,"Chang"
,"Klein"
,"Salinas"
,"Fuentes"
,"Baldwin"
,"Daniel"
,"Simon"
,"Velasquez"
,"Hardy"
,"Higgins"
,"Aguirre"
,"Lin"
,"Cummings"
,"Chandler"
,"Sharp"
,"Barber"
,"Bowen"
,"Ochoa"
,"Dennis"
,"Robbins"
,"Liu"
,"Ramsey"
,"Francis"
,"Griffith"
,"Paul"
,"Blair"
,"Oconnor"
,"Cardenas"
,"Pacheco"
,"Cross"
,"Calderon"
,"Quinn"
,"Moss"
,"Swanson"
,"Chan"
,"Rivas"
,"Khan"
,"Rodgers"
,"Serrano"
,"Fitzgerald"
,"Rosales"
,"Stevenson"
,"Christensen"
,"Manning"
,"Gill"
,"Curry"
,"Mclaughlin"
,"Harmon"
,"Mcgee"
,"Gross"
,"Doyle"
,"Garner"
,"Newton"
,"Burgess"
,"Reese"
,"Walton"
,"Blake"
,"Trujillo"
,"Adkins"
,"Brady"
,"Goodman"
,"Roman"
,"Webster"
,"Goodwin"
,"Fischer"
,"Huang"
,"Potter"
,"Delacruz"
,"Montoya"
,"Todd"
,"Wu"
,"Hines"
,"Mullins"
,"Castaneda"
,"Malone"
,"Cannon"
,"Tate"
,"Mack"
,"Sherman"
,"Hubbard"
,"Hodges"
,"Zhang"
,"Guerra"
,"Wolf"
,"Valencia"
,"Franco"
,"Saunders"
,"Rowe"
,"Gallagher"
,"Farmer"
,"Hammond"
,"Hampton"
,"Townsend"
,"Ingram"
,"Wise"
,"Gallegos"
,"Clarke"
,"Barton"
,"Schroeder"
,"Maxwell"
,"Waters"
,"Logan"
,"Camacho"
,"Strickland"
,"Norman"
,"Person"
,"Colon"
,"Parsons"
,"Frank"
,"Harrington"
,"Glover"
,"Osborne"
,"Buchanan"
,"Casey"
,"Floyd"
,"Patton"
,"Ibarra"
,"Ball"
,"Tyler"
,"Suarez"
,"Bowers"
,"Orozco"
,"Salas"
,"Cobb"
,"Gibbs"
,"Andrade"
,"Bauer"
,"Conner"
,"Moody"
,"Escobar"
,"Mcguire"
,"Lloyd"
,"Mueller"
,"Hartman"
,"French"
,"Kramer"
,"Mcbride"
,"Pope"
,"Lindsey"
,"Velazquez"
,"Norton"
,"Mccormick"
,"Sparks"
,"Flynn"
,"Yates"
,"Hogan"
,"Marsh"
,"Macias"
,"Villanueva"
,"Zamora"
,"Pratt"
,"Stokes"
,"Owen"
,"Ballard"
,"Lang"
,"Brock"
,"Villarreal"
,"Charles"
,"Drake"
,"Barrera"
,"Cain"
,"Patrick"
,"Pineda"
,"Burnett"
,"Mercado"
,"Santana"
,"Shepherd"
,"Bautista"
,"Ali"
,"Shaffer"
,"Lamb"
,"Trevino"
,"Mckenzie"
,"Hess"
,"Beil"
,"Olsen"
,"Cochran"
,"Morton"
,"Nash"
,"Wilkins"
,"Petersen"
,"Briggs"
,"Shah"
,"Roth"
,"Nicholson"
,"Holloway"
,"Lozano"
,"Flowers"
,"Rangel"
,"Hoover"
,"Arias"
,"Short"
,"Mora"
,"Valenzuela"
,"Bryan"
,"Meyers"
,"Weiss"
,"Underwood"
,"Bass"
,"Greer"
,"Summers"
,"Houston"
,"Carson"
,"Morrow"
,"Clayton"
,"Whitaker"
,"Decker"
,"Yoder"
,"Collier"
,"Zuniga"
,"Carey"
,"Wilcox"
,"Melendez"
,"Poole"
,"Roberson"
,"Larsen"
,"Conley"
,"Davenport"
,"Copeland"
,"Massey"
,"Lam"
,"Huff"
,"Rocha"
,"Cameron"
,"Jefferson"
,"Hood"
,"Monroe"
,"Anthony"
,"Pittman"
,"Huynh"
,"Randall"
,"Singleton"
,"Kirk"
,"Combs"
,"Mathis"
,"Christian"
,"Skinner"
,"Bradford"
,"Richard"
,"Galvan"
,"Wall"
,"Boone"
,"Kirby"
,"Wilkinson"
,"Bridges"
,"Bruce"
,"Atkinson"
,"Velez"
,"Meza"
,"Roy"
,"Vincent"
,"York"
,"Hodge"
,"Villa"
,"Abbott"
,"Allison"
,"Tapia"
,"Gates"
,"Chase"
,"Sosa"
,"Sweeney"
,"Farrell"
,"Wyatt"
,"Dalton"
,"Horn"
,"Barron"
,"Phelps"
,"Yu"
,"Dickerson"
,"Heath"
,"Foley"
,"Atkins"
,"Mathews"
,"Bonilla"
,"Acevedo"
,"Benitez"
,"Zavala"
,"Hensley"
,"Glenn"
,"Cisneros"
,"Harrell"
,"Shields"
,"Rubio"
,"Choi"
,"Huffman"
,"Boyer"
,"Garrison"
,"Arroyo"
,"Bond"
,"Kane"
,"Hancock"
,"Callahan"
,"Dillon"
,"Cline"
,"Wiggins"
,"Grimes"
,"Arellano"
,"Melton"
,"Oneill"
,"Savage"
,"Ho"
,"Beltran"
,"Pitts"
,"Parrish"
,"Ponce"
,"Rich"
,"Booth"
,"Koch"
,"Golden"
,"Ware"
,"Brennan"
,"Mcdowell"
,"Marks"
,"Cantu"
,"Humphrey"
,"Baxter"
,"Sawyer"
,"Clay"
,"Tanner"
,"Hutchinson"
,"Kaur"
,"Berg"
,"Wiley"
,"Gilmore"
,"Russo"
,"Villegas"
,"Hobbs"
,"Keith"
,"Wilkerson"
,"Ahmed"
,"Beard"
,"Mcclain"
,"Montes"
,"Mata"
,"Rosario"
,"Vang"
,"S"
,"S"
,"Walter"
,"Henson"
,"Oneal"
,"Mosley"
,"Mcclure"
,"Beasley"
,"Stephenson"
,"Snow"
,"Huerta"
,"Preston"
,"Vance"
,"Barry"
,"Johns"
,"Eaton"
,"Blackwell"
,"Dyer"
,"Prince"
,"Macdonald"
,"Solomon"
,"Guevara"
,"Stafford"
,"English"
,"Hurst"
,"Woodard"
,"Cortes"
,"Shannon"
,"Kemp"
,"Nolan"
,"Mccullough"
,"Merritt"
,"Murillo"
,"Moon"
,"Salgado"
,"Strong"
,"Kline"
,"Cordova"
,"Barajas"
,"Roach"
,"Rosas"
,"Winters"
,"Jacobson"
,"Lester"
,"Knox"
,"Bullock"
,"Kerr"
,"Leach"
,"Meadows"
,"Davila"
,"Orr"
,"Whitehead"
,"Pruitt"
,"Kent"
,"Conway"
,"Mckee"
,"Barr"
,"David"
,"Dejesus"
,"Marin"
,"Berger"
,"Mcintyre"
,"Blankenship"
,"Gaines"
,"Palacios"
,"Cuevas"
,"Bartlett"
,"Durham"
,"Dorsey"
,"Mccall"
,"Odonnell"
,"Stein"
,"Browning"
,"Stout"
,"Lowery"
,"Sloan"
,"Mclean"
,"Hendricks"
,"Calhoun"
,"Sexton"
,"Chung"
,"Gentry"
,"Hull"
,"Duarte"
,"Ellison"
,"Nielsen"
,"Gillespie"
,"Buck"
,"Middleton"
,"Sellers"
,"Leblanc"
,"Esparza"
,"Hardin"
,"Bradshaw"
,"Mcintosh"
,"Howe"
,"Livingston"
,"Frost"
,"Glass"
,"Morse"
,"Knapp"
,"Herman"
,"Stark"
,"Bravo"
,"Noble"
,"Spears"
,"Weeks"
,"Corona"
,"Frederick"
,"Buckley"
,"Mcfarland"
,"Hebert"
,"Enriquez"
,"Hickman"
,"Quintero"
,"Randolph"
,"Schaefer"
,"Walls"
,"Trejo"
,"House"
,"Reilly"
,"Pennington"
,"Michael"
,"Conrad"
,"Giles"
,"Benjamin"
,"Crosby"
,"Fitzpatrick"
,"Donovan"
,"Mays"
,"Mahoney"
,"Valentine"
,"Raymond"
,"Medrano"
,"Hahn"
,"Mcmillan"
,"Small"
,"Bentley"
,"Felix"
,"Peck"
,"Lucero"
,"Boyle"
,"Hanna"
,"Pace"
,"Rush"
,"Hurley"
,"Harding"
,"Mcconnell"
,"Bernal"
,"Nava"
,"Ayers"
,"Everett"
,"Ventura"
,"Avery"
,"Pugh"
,"Mayer"
,"Bender"
,"Shepard"
,"Mcmahon"
,"Landry"
,"Case"
,"Sampson"
,"Moses"
,"Magana"
,"Blackburn"
,"Dunlap"
,"Gould"
,"Duffy"
,"Vaughan"
,"Herring"
,"Mckay"
,"Espinosa"
,"Rivers"
,"Farley"
,"Bernard"
,"Ashley"
,"Friedman"
,"Potts"
,"Truong"
,"Costa"
,"Correa"
,"Blevins"
,"Nixon"
,"Clements"
,"Fry"
,"Delarosa"
,"Best"
,"Benton"
,"Lugo"
,"Portillo"
,"Dougherty"
,"Crane"
,"Haley"
,"Phan"
,"Villalobos"
,"Blanchard"
,"Horne"
,"Finley"
,"Quintana"
,"Lynn"
,"Esquivel"
,"Bean"
,"Dodson"
,"Mullen"
,"Xiong"
,"Hayden"
,"Cano"
,"Levy"
,"Huber"
,"Richmond"
,"Moyer"
,"Lim"
,"Frye"
,"Sheppard"
,"Mccarty"
,"Avalos"
,"Booker"
,"Waller"
,"Parra"
,"Woodward"
,"Jaramillo"
,"Krueger"
,"Rasmussen"
,"Brandt"
,"Peralta"
,"Donaldson"
,"Stuart"
,"Faulkner"
,"Maynard"
,"Galindo"
,"Coffey"
,"Estes"
,"Sanford"
,"Burch"
,"Maddox"
,"Vo"
,"Oconnell"
,"Vu"
,"S"
,"S"
,"Andersen"
,"Spence"
,"Mcpherson"
,"Church"
,"Schmitt"
,"Stanton"
,"Leal"
,"Cherry"
,"Compton"
,"Dudley"
,"Sierra"
,"Pollard"
,"Alfaro"
,"Hester"
,"Proctor"
,"Lu"
,"Hinton"
,"Novak"
,"Good"
,"Madden"
,"Mccann"
,"Terrell"
,"Jarvis"
,"Dickson"
,"Reyna"
,"Cantrell"
,"Mayo"
,"Branch"
,"Hendrix"
,"Rollins"
,"Rowland"
,"Whitney"
,"Duke"
,"Odom"
};
        }

        public List<string> GetFemaleFirstnames()
        {
            return new List<string>() {
    "Olivia"
    ,"Emma"
    ,"Charlotte"
    ,"Amelia"
    ,"Sophia"
    ,"Isabella"
    ,"Ava"
    ,"Mia"
    ,"Evelyn"
    ,"Luna"
    ,"Harper"
    ,"Camila"
    ,"Sofia"
    ,"Scarlett"
    ,"Elizabeth"
    ,"Eleanor"
    ,"Emily"
    ,"Chloe"
    ,"Mila"
    ,"Violet"
    ,"Penelope"
    ,"Gianna"
    ,"Aria"
    ,"Abigail"
    ,"Ella"
    ,"Avery"
    ,"Hazel"
    ,"Nora"
    ,"Layla"
    ,"Lily"
    ,"Aurora"
    ,"Nova"
    ,"Ellie"
    ,"Madison"
    ,"Grace"
    ,"Isla"
    ,"Willow"
    ,"Zoe"
    ,"Riley"
    ,"Stella"
    ,"Eliana"
    ,"Ivy"
    ,"Victoria"
    ,"Emilia"
    ,"Zoey"
    ,"Naomi"
    ,"Hannah"
    ,"Lucy"
    ,"Elena"
    ,"Lillian"
    ,"Maya"
    ,"Leah"
    ,"Paisley"
    ,"Addison"
    ,"Natalie"
    ,"Valentina"
    ,"Everly"
    ,"Delilah"
    ,"Leilani"
    ,"Madelyn"
    ,"Kinsley"
    ,"Ruby"
    ,"Sophie"
    ,"Alice"
    ,"Genesis"
    ,"Claire"
    ,"Audrey"
    ,"Sadie"
    ,"Aaliyah"
    ,"Josephine"
    ,"Autumn"
    ,"Brooklyn"
    ,"Quinn"
    ,"Kennedy"
    ,"Cora"
    ,"Savannah"
    ,"Caroline"
    ,"Athena"
    ,"Natalia"
    ,"Hailey"
    ,"Aubrey"
    ,"Emery"
    ,"Anna"
    ,"Iris"
    ,"Bella"
    ,"Eloise"
    ,"Skylar"
    ,"Jade"
    ,"Gabriella"
    ,"Ariana"
    ,"Maria"
    ,"Adeline"
    ,"Lydia"
    ,"Sarah"
    ,"Nevaeh"
    ,"Serenity"
    ,"Liliana"
    ,"Ayla"
    ,"Everleigh"
    ,"Raelynn"
    ,"Allison"
    ,"Madeline"
    ,"Vivian"
    ,"Maeve"
    ,"Lyla"
    ,"Samantha"
    ,"Rylee"
    ,"Eva"
    ,"Melody"
    ,"Clara"
    ,"Hadley"
    ,"Julia"
    ,"Piper"
    ,"Juniper"
    ,"Parker"
    ,"Brielle"
    ,"Eden"
    ,"Remi"
    ,"Josie"
    ,"Rose"
    ,"Arya"
    ,"Eliza"
    ,"Charlie"
    ,"Peyton"
    ,"Daisy"
    ,"Lucia"
    ,"Millie"
    ,"Margaret"
    ,"Freya"
    ,"Melanie"
    ,"Elliana"
    ,"Adalynn"
    ,"Alina"
    ,"Emersyn"
    ,"Sienna"
    ,"Mary"
    ,"Isabelle"
    ,"Alaia"
    ,"Esther"
    ,"Sloane"
    ,"Mackenzie"
    ,"Amara"
    ,"Ximena"
    ,"Sage"
    ,"Cecilia"
    ,"Valeria"
    ,"Reagan"
    ,"Valerie"
    ,"Catalina"
    ,"River"
    ,"Magnolia"
    ,"Kehlani"
    ,"Summer"
    ,"Ashley"
    ,"Andrea"
    ,"Isabel"
    ,"Oakley"
    ,"Olive"
    ,"Oaklynn"
    ,"Ember"
    ,"Kaylee"
    ,"Georgia"
    ,"Juliette"
    ,"Anastasia"
    ,"Genevieve"
    ,"Katherine"
    ,"Blakely"
    ,"Reese"
    ,"Amaya"
    ,"Emerson"
    ,"Brianna"
    ,"June"
    ,"Alani"
    ,"Lainey"
    ,"Arianna"
    ,"Rosalie"
    ,"Sara"
    ,"Jasmine"
    ,"Ruth"
    ,"Adalyn"
    ,"Ada"
    ,"Bailey"
    ,"Ariella"
    ,"Wren"
    ,"Myla"
    ,"Khloe"
    ,"Callie"
    ,"Elsie"
    ,"Alexandra"
    ,"Ryleigh"
    ,"Faith"
    ,"Norah"
    ,"Margot"
    ,"Zuri"
    ,"Journee"
    ,"Aspen"
    ,"Gemma"
    ,"Kylie"
    ,"Molly"
    ,"Blake"
    ,"Zara"
    ,"Alaina"
    ,"Alana"
    ,"Brynlee"
    ,"Amy"
    ,"Annie"
    ,"Saylor"
    ,"Ana"
    ,"Amira"
    ,"Kimberly"
    ,"Noelle"
    ,"Kamila"
    ,"Morgan"
    ,"Phoebe"
    ,"Harmony"
    ,"Sutton"
    ,"Taylor"
    ,"Finley"
    ,"Lilah"
    ,"Juliana"
    ,"Lila"
    ,"Londyn"
    ,"Kailani"
    ,"Vera"
    ,"Kaia"
    ,"Angela"
    ,"Hallie"
    ,"Diana"
    ,"Lennon"
    ,"Presley"
    ,"Arabella"
    ,"Aliyah"
    ,"Lilly"
    ,"Milani"
    ,"Jordyn"
    ,"Camille"
    ,"Ariel"
    ,"Aubree"
    ,"Selena"
    ,"Sawyer"
    ,"Nyla"
    ,"Delaney"
    ,"Mariana"
    ,"Rachel"
    ,"Adaline"
    ,"Leila"
    ,"Collins"
    ,"Lia"
    ,"Octavia"
    ,"Kali"
    ,"Lena"
    ,"Kiara"
    ,"Kaylani"
    ,"Elaina"
    ,"Daniela"
    ,"Leia"
    ,"Gracie"
    ,"Dakota"
    ,"Elise"
    ,"Hope"
    ,"Harlow"
    ,"Lola"
    ,"Stevie"
    ,"Malia"
    ,"Miriam"
    ,"Alora"
    ,"Gia"
    ,"Evangeline"
    ,"Brooke"
    ,"Lilith"
    ,"Sydney"
    ,"Ophelia"
    ,"Alayna"
    ,"Tatum"
    ,"Evie"
    ,"Rowan"
    ,"Marley"
    ,"Daphne"
    ,"Kayla"
    ,"Dahlia"
    ,"Lucille"
    ,"Blair"
    ,"Adelaide"
    ,"Wrenley"
    ,"Haven"
    ,"Teagan"
    ,"Adelyn"
    ,"Alyssa"
    ,"Payton"
    ,"Jane"
    ,"Mckenna"
    ,"Celeste"
    ,"Juliet"
    ,"Palmer"
    ,"Maggie"
    ,"Rebecca"
    ,"London"
    ,"Noa"
    ,"Samara"
    ,"Thea"
    ,"Kendall"
    ,"Mya"
    ,"Talia"
    ,"Winter"
    ,"Angelina"
    ,"Vivienne"
    ,"Esme"
    ,"Laila"
    ,"Nina"
    ,"Trinity"
    ,"Vanessa"
    ,"Mabel"
    ,"Camilla"
    ,"Jocelyn"
    ,"Journey"
    ,"Paige"
    ,"Phoenix"
    ,"Amina"
    ,"Alivia"
    ,"Amari"
    ,"Joanna"
    ,"Nicole"
    ,"Annabelle"
    ,"Raegan"
    ,"Aitana"
    ,"Julianna"
    ,"Lauren"
    ,"Catherine"
    ,"Adriana"
    ,"Madilyn"
    ,"Harley"
    ,"Tessa"
    ,"Evelynn"
    ,"Elianna"
    ,"Rory"
    ,"Dream"
    ,"Nayeli"
    ,"Poppy"
    ,"Gabriela"
    ,"Jayla"
    ,"Cataleya"
    ,"Celine"
    ,"Hayden"
    ,"Shiloh"
    ,"Mariah"
    ,"Charlee"
    ,"Maisie"
    ,"Regina"
    ,"Adelynn"
    ,"Briella"
    ,"Giselle"
    ,"Fatima"
    ,"Danna"
    ,"Alessia"
    ,"Mckenzie"
    ,"Wynter"
    ,"Fiona"
    ,"Brooklynn"
    ,"Gracelynn"
    ,"Luciana"
    ,"Alexis"
    ,"Everlee"
    ,"Laura"
    ,"Selah"
    ,"Reign"
    ,"Alayah"
    ,"Rosemary"
    ,"Lilliana"
    ,"Ariyah"
    ,"Heidi"
    ,"Esmeralda"
    ,"Logan"
    ,"Amora"
    ,"Kalani"
    ,"Leighton"
    ,"Cali"
    ,"Melissa"
    ,"Aniyah"
    ,"Izabella"
    ,"Michelle"
    ,"Raelyn"
    ,"Alessandra"
    ,"Viviana"
    ,"Madeleine"
    ,"Arielle"
    ,"Serena"
    ,"Francesca"
    ,"Brynn"
    ,"Gwendolyn"
    ,"Kira"
    ,"Destiny"
    ,"Elle"
    ,"Makayla"
    ,"Alaya"
    ,"Malani"
    ,"Willa"
    ,"Saige"
    ,"Makenna"
    ,"Remington"
    ,"Demi"
    ,"Adelina"
    ,"Raya"
    ,"Astrid"
    ,"Azalea"
    ,"Veronica"
    ,"Meadow"
    ,"Anaya"
    ,"Elisa"
    ,"Raven"
    ,"Alexandria"
    ,"Hattie"
    ,"Alicia"
    ,"Sabrina"
    ,"Gracelyn"
    ,"Matilda"
    ,"Skye"
    ,"Annalise"
    ,"Frances"
    ,"Miracle"
    ,"Maia"
    ,"Helen"
    ,"Lana"
    ,"Daleyza"
    ,"Rosie"
    ,"Charli"
    ,"Bianca"
    ,"Royalty"
    ,"Sarai"
    ,"Amiyah"
    ,"Nylah"
    ,"Aylin"
    ,"Maryam"
    ,"Scarlet"
    ,"Antonella"
    ,"Sylvia"
    ,"Sylvie"
    ,"Nadia"
    ,"Ari"
    ,"Lexi"
    ,"Mylah"
    ,"Julieta"
    ,"Lorelei"
    ,"Avianna"
    ,"Armani"
    ,"Camryn"
    ,"Emely"
    ,"Rylie"
    ,"Colette"
    ,"Daniella"
    ,"Liana"
    ,"Brinley"
    ,"Kate"
    ,"Salem"
    ,"Marlee"
    ,"Alison"
    ,"Carmen"
    ,"Felicity"
    ,"Fernanda"
    ,"Holly"
    ,"Ariah"
    ,"Aisha"
    ,"Kora"
    ,"Amanda"
    ,"Ailani"
    ,"Elaine"
    ,"Emory"
    ,"Joy"
    ,"Oaklee"
    ,"Lyric"
    ,"Madelynn"
    ,"Haisley"
    ,"Allie"
    ,"Helena"
    ,"Danielle"
    ,"Katalina"
    ,"Carolina"
    ,"Zariah"
    ,"Navy"
    ,"Cassidy"
    ,"Lorelai"
    ,"Stephanie"
    ,"Alma"
    ,"Mira"
    ,"Legacy"
    ,"Jolene"
    ,"Anya"
    ,"Dorothy"
    ,"Paris"
    ,"Yaretzi"
    ,"Aurelia"
    ,"Maddison"
    ,"Renata"
    ,"Jimena"
    ,"Xiomara"
    ,"Itzel"
    ,"Heaven"
    ,"Lyra"
    ,"Estella"
    ,"Gabrielle"
    ,"Maren"
    ,"Jacqueline"
    ,"Jennifer"
    ,"Imani"
    ,"Jordan"
    ,"Paislee"
    ,"Ainsley"
    ,"Emmy"
    ,"Jessica"
    ,"Alondra"
    ,"Mae"
    ,"Makenzie"
    ,"Bristol"
    ,"Edith"
    ,"Cameron"
    ,"Elora"
    ,"Jazlyn"
    ,"Averie"
    ,"Ivory"
    ,"Kenzie"
    ,"Emelia"
    ,"Angel"
    ,"Cecelia"
    ,"Maliyah"
    ,"Oakleigh"
    ,"Opal"
    ,"Oaklyn"
    ,"Kinley"
    ,"Kayleigh"
    ,"Bonnie"
    ,"April"
    ,"Kamryn"
    ,"Mallory"
    ,"Briar"
    ,"Leona"
    ,"Keira"
    ,"Alexa"
    ,"Macie"
    ,"Ariya"
    ,"Briana"
    ,"Virginia"
    ,"Skyler"
    ,"Amber"
    ,"Hanna"
    ,"Monroe"
    ,"Frankie"
    ,"Miranda"
    ,"Dayana"
    ,"Charleigh"
    ,"Meredith"
    ,"Carter"
    ,"Sierra"
    ,"Sunny"
    ,"Indie"
    ,"Eve"
    ,"Beatrice"
    ,"Nalani"
    ,"Kyla"
    ,"Clementine"
    ,"Katie"
    ,"Kennedi"
    ,"Myra"
    ,"Blaire"
    ,"Davina"
    ,"Faye"
    ,"Anahi"
    ,"Madilynn"
    ,"Alejandra"
    ,"Alanna"
    ,"Ivanna"
    ,"Mariam"
    ,"Yara"
    ,"Anne"
    ,"Addilyn"
    ,"Braelynn"
    ,"Lilian"
    ,"Dylan"
    ,"Amirah"
    ,"Lina"
    ,"Reyna"
    ,"Amalia"
    ,"Amani"
    ,"Ryan"
    ,"Calliope"
    ,"Isabela"
    ,"Michaela"
    ,"Abby"
    ,"Alia"
    ,"Emerie"
    ,"Lylah"
    ,"Holland"
    ,"Sevyn"
    ,"Winnie"
    ,"Leyla"
    ,"Shelby"
    ,"Rosalia"
    ,"Zariyah"
    ,"Rhea"
    ,"Emberly"
    ,"Marie"
    ,"Nia"
    ,"Remy"
    ,"Chaya"
    ,"Haley"
    ,"Kaliyah"
    ,"Rosa"
    ,"Zahra"
    ,"Jayleen"
    ,"Karsyn"
    ,"Malaysia"
    ,"Jaliyah"
    ,"Mina"
    ,"Kensley"
    ,"Lennox"
    ,"Maxine"
    ,"Hadassah"
    ,"Mikayla"
    ,"Margo"
    ,"Noah"
    ,"Azariah"
    ,"Mara"
    ,"Eileen"
    ,"Florence"
    ,"Melany"
    ,"Reina"
    ,"Journi"
    ,"Amaia"
    ,"Kaitlyn"
    ,"Elliott"
    ,"Kelsey"
    ,"Nola"
    ,"Gloria"
    ,"Keilani"
    ,"Freyja"
    ,"Arleth"
    ,"Jenna"
    ,"Sloan"
    ,"Analia"
    ,"Louise"
    ,"Melina"
    ,"Sasha"
    ,"Dior"
    ,"Thalia"
    ,"Noemi"
    ,"Maci"
    ,"Dallas"
    ,"Marina"
    ,"Aliana"
    ,"Ezra"
    ,"Adley"
    ,"Cassandra"
    ,"Aleena"
    ,"Leslie"
    ,"Capri"
    ,"Mckinley"
    ,"Angelica"
    ,"Romina"
    ,"Della"
    ,"Kathryn"
    ,"Kyra"
    ,"Milan"
    ,"Tiana"
    ,"Khaleesi"
    ,"Nellie"
    ,"Cleo"
    ,"Murphy"
    ,"Bethany"
    ,"Irene"
    ,"Ellianna"
    ,"Zelda"
    ,"Aleah"
    ,"Janelle"
    ,"Yareli"
    ,"Adalee"
    ,"Dani"
    ,"Marceline"
    ,"Coraline"
    ,"Estrella"
    ,"Ila"
    ,"Iyla"
    ,"Mavis"
    ,"Kenna"
    ,"Vienna"
    ,"Zendaya"
    ,"Cheyenne"
    ,"Erin"
    ,"Karla"
    ,"Mikaela"
    ,"Jazmin"
    ,"Persephone"
    ,"Elodie"
    ,"Selene"
    ,"Chelsea"
    ,"Scout"
    ,"Theodora"
    ,"Lara"
    ,"Marilyn"
    ,"Novah"
    ,"Ellis"
    ,"Charley"
    ,"Jemma"
    ,"Amayah"
    ,"Karina"
    ,"Kendra"
    ,"Miley"
    ,"Laney"
    ,"Laurel"
    ,"Leilany"
    ,"Halle"
    ,"Jenesis"
    ,"Malaya"
    ,"Marleigh"
    ,"Wrenlee"
    ,"Zaylee"
    ,"Fallon"
    ,"Julie"
    ,"Priscilla"
    ,"Bellamy"
    ,"Adrianna"
    ,"Angie"
    ,"Siena"
    ,"Aileen"
    ,"Macy"
    ,"Estelle"
    ,"Hana"
    ,"Martha"
    ,"Flora"
    ,"Kylee"
    ,"Liv"
    ,"Megan"
    ,"Sariyah"
    ,"Galilea"
    ,"Penny"
    ,"Jovie"
    ,"Jamie"
    ,"Amoura"
    ,"Emmie"
    ,"Henley"
    ,"Sky"
    ,"Christina"
    ,"Violeta"
    ,"Arlet"
    ,"Belen"
    ,"Aviana"
    ,"Kori"
    ,"Monica"
    ,"Savanna"
    ,"Naya"
    ,"Alena"
    ,"Aya"
    ,"Waverly"
    ,"Brynleigh"
    ,"Aliza"
    ,"Kiana"
    ,"Love"
    ,"Clover"
    ,"Pearl"
    ,"Skyla"
    ,"Bria"
    ,"Ocean"
    ,"Alisson"
    ,"Treasure"
    ,"Lillie"
    ,"Jaylani"
    ,"Liberty"
    ,"Rayna"
    ,"Milana"
    ,"Zaria"
    ,"Emerald"
    ,"Halo"
    ,"Taytum"
    ,"Andi"
    ,"Milena"
    ,"Noor"
    ,"Kataleya"
    ,"Kimber"
    ,"Carly"
    ,"Jream"
    ,"Samira"
    ,"Ashlyn"
    ,"Hunter"
    ,"Marlowe"
    ,"Promise"
    ,"Joelle"
    ,"Dulce"
    ,"Lea"
    ,"Ashlynn"
    ,"Zoya"
    ,"Elliot"
    ,"Jolie"
    ,"Kai"
    ,"Bridget"
    ,"Johanna"
    ,"Paulina"
    ,"Ramona"
    ,"Aila"
    ,"Jessie"
    ,"Mercy"
    ,"Rayne"
    ,"Rivka"
    ,"Arlette"
    ,"Paula"
    ,"Valery"
    ,"Birdie"
    ,"Nala"
    ,"Kelly"
    ,"Kinslee"
    ,"Linda"
    ,"Madisyn"
    ,"Aspyn"
    ,"Baylor"
    ,"Chana"
    ,"Zaniyah"
    ,"Goldie"
    ,"Marianna"
    ,"Novalee"
    ,"Loretta"
    ,"Elyse"
    ,"Stormi"
    ,"Adele"
    ,"Berkley"
    ,"Anika"
    ,"Marisol"
    ,"Kassidy"
    ,"Roselyn"
    ,"Louisa"
    ,"Alexia"
    ,"Dalia"
    ,"Ensley"
    ,"Hayley"
    ,"Jayda"
    ,"Harmoni"
    ,"Jada"
    ,"Marigold"
    ,"Zayla"
    ,"Ayleen"
    ,"Natasha"
    ,"Sol"
    ,"Annika"
    ,"Malayah"
    ,"Drew"
    ,"Anais"
    ,"Angelique"
    ,"Zhuri"
    ,"Aliya"
    ,"Azaria"
    ,"Zora"
    ,"Allyson"
    ,"Brittany"
    ,"Kamiyah"
    ,"Gwen"
    ,"Vada"
    ,"Giuliana"
    ,"Elina"
    ,"Hadlee"
    ,"Itzayana"
    ,"Jianna"
    ,"Cadence"
    ,"Greta"
    ,"Lilianna"
    ,"Denver"
    ,"Robin"
    ,"August"
    ,"Jazmine"
    ,"Royal"
    ,"Braelyn"
    ,"Celia"
    ,"Yamileth"
    ,"Avayah"
    ,"Baylee"
    ,"Iliana"
    ,"Teresa"
    ,"Amelie"
    ,"Judith"
    ,"Kara"
    ,"Lacey"
    ,"Amiri"
    ,"Elowyn"
    ,"Georgina"
    ,"Justice"
    ,"Emmalyn"
    ,"Harlee"
    ,"Kamari"
    ,"Kaydence"
    ,"Khalani"
    ,"Luisa"
    ,"Whitley"
    ,"Bailee"
    ,"Cynthia"
    ,"Karter"
    ,"Livia"
    ,"Aubrie"
    ,"Veda"
    ,"Janiyah"
    ,"Salma"
    ,"Araya"
    ,"Aubrielle"
    ,"Bexley"
    ,"Giana"
    ,"Keyla"
    ,"Katelyn"
    ,"Saoirse"
    ,"Sariah"
    ,"Araceli"
    ,"Artemis"
    ,"Averi"
    ,"Yasmin"
    ,"Kaiya"
    ,"Emberlynn"
    ,"Amaris"
    ,"Sapphire"
    ,"Kallie"
    ,"Shay"
    ,"Guinevere"
    ,"Lilyana"
    ,"Magdalena"
    ,"Tinsley"
    ,"Zainab"
    ,"Deborah"
    ,"Kenia"
    ,"Laylah"
    ,"Layne"
    ,"Scottie"
    ,"Carla"
    ,"Chandler"
    ,"Rosalina"
    ,"Kairi"
    ,"Lauryn"
    ,"Nyomi"
    ,"Raina"
    ,"Aubriella"
    ,"Elia"
    ,"Lenora"
    ,"Lisa"
    ,"Nori"
    ,"Tiffany"
    ,"Giovanna"
    ,"Jaylah"
    ,"Rosalyn"
    ,"Chanel"
    ,"Maddie"
    ,"Avah"
    ,"Leanna"
    ,"Luz"
    ,"Addilynn"
    ,"Brylee"
    ,"Casey"
    ,"Laylani"
    ,"Tru"
    ,"Billie"
    ,"Lottie"
    ,"Alianna"
    ,"Meilani"
    ,"Lexie"
    ,"Nathalia"
    ,"Avalynn"
    ,"Julissa"
    ,"Paloma"
    ,"Rosalee"
    ,"Rebekah"
    ,"Simone"
    ,"Egypt"
    ,"Scarlette"
    ,"Sarahi"
    ,"Alaiya"
    ,"Hadleigh"
    ,"Inaya"
    ,"Keily"
    ,"Lakelynn"
    ,"Nyra"
    ,"Princess"
    ,"Rowyn"
    ,"Vida"
    ,"Elisabeth"
    ,"India"
    ,"Ryann"
    ,"Barbara"
    ,"Belle"
    ,"Saanvi"
    ,"Xyla"
    ,"Winona"
    ,"Aadhya"
    ,"Indigo"
    ,"Lakelyn"
    ,"Paola"
    ,"Emmeline"
    ,"Joyce"
    ,"Kamilah"
    ,"Maisy"
    ,"Rylan"
    ,"Soleil"
    ,"Ainhoa"
    ,"Maleah"
    ,"Neriah"
    ,"Elsa"
    ,"Emiliana"
    ,"Luella"
    ,"Nancy"
    ,"Cielo"
    ,"Madalyn"
    ,"Kahlani"
    };
        }

        public List<string> GetUsernames()
        {
            return new List<string>(){
    "MexicanDjango"
    ,"ApocalypseMan"
    ,"Bangarmor"
    ,"BigMacSandWitch"
    ,"AwesomeHobo"
    ,"OneLoneClone"
    ,"SilverStoneGunner"
    ,"MustacheMopol"
    ,"TheFinalCountdown"
    ,"Spawn99"
    ,"MasterKeef"
    ,"Apocalypse3434"
    ,"LookWhatICanDo"
    ,"NoNoob"
    ,"LeSpank"
    ,"RufioRoofie"
    ,"SkyxQueen"
    ,"TornadoArtillery"
    ,"SupraNova"
    ,"TheORacle"
    ,"SpeedBreaker"
    ,"SunVolt"
    ,"Swampmasher"
    ,"WarningLowBattery"
    ,"RedLiquidShrapnel"
    ,"TheMustardCat"
    ,"BigPapa"
    ,"WhoWasThat"
    ,"SmittenKitten66"
    ,"MasterBeast"
    ,"CrazedMaaana"
    ,"SniperPrincess"
    ,"MsPiggysRevenge"
    ,"PistolPrincess"
    ,"BigMastadon"
    ,"HilariousVader"
    ,"SweetAngryJesus"
    ,"HomelessPower"
    ,"RockYourDead"
    ,"ElitistBastard","SereneSavage"
    ,"CosmicFunkSquad","BestGamerPeriod"
    ,"SmokinHotChick","BettyBoopsBoop"
    ,"cereal_killer","GodofWar"
    ,"GodessofWar","BabyBluez"
    ,"TheMilkyWeigh","HotButteryPopcorn"
    ,"TheNastyPasty","PaniniHead"
    ,"IYELLALOT"
    ," PawneeGoddess ","SilentFalcon13"
    ,"PheonixFire56"
    ,"BlitZucchini","TWitMeet"
    ,"Tacklebox"
    ,"Tough Nut","Bonzai"
    ,"FireByMisFire"
    ,"Fat Tony","The Cougar"
    ,"FlyGuardX","Ghostrider","JesterZilla"
    ,"JigKraken","K-Tin Man"
    ,"Keystone","Nutmeg Riot"
    ,"RadioactiveMan"
    ,"Raid Bucker"
    ,"Saint La-Z-Boy"
    ,"RevengeOfOmega"
    ,"Scrapper"
    ,"SpellTansy"
    ,"ToxicCharger"
    ,"TrixiePhany"
    ,"PlasmaSponge"
    ,"GruntBoBnoPants"
    ,"PonySlaystation"
    ,"Callmesensei"
    ,"RoyaleWCheese"
    ,"PeriodPains"
    ,"Missbehave"
    ,"LaDiabla"
    ,"NowYouSeeMe"
    ,"CrouchingTiger"
    ,"Asasinsensation"
    ,"Turdinator"
    ,"Vortex"
    ,"MISTIK31"
    ,"TheSilentBang"
    ,"Zeldarian"
    ,"ArcticBlade"
    ,"Error404"
    ,"BegForMercy"
    ,"Zozo"
    ,"bazinga!"
    ,"Toxic Headshot"
    ,"Frozen Gunner"
    ,"Masked Titan"
    ,"UltimateBeast"
    ,"FatalDestiny"
    ,"DarkCarnage"
    ,"StealthedDefende"
    ,"Blaze Assault"
    ,"TurboSlayer"
    ,"Bad2TheBone"
    ,"KnifeInGutsOut"
    ,"NoMercy4TheWeak"
    ,"EatBullets"
    ,"TeKillaSunrise"
    ,"SkullCrusher"
    ,"kiss-my-axe"
    ,"ScarOnYourFace"
    ,"SmokinAces"
    ,"T3rr0r1st"
    ,"TakinOutThaTrash"
    ,"TheButcher"
    ,"TheSickness"
    ,"Shoot2Kill"
    ,"Overkill"
    ,"Killspree"
    ,"Psychopath"
    ,"Born2Kill"
    ,"BloodyKnuckles"
    ,"LocalBackStabber"
    ,"TheButcher"
    ,"ChopChop"
    ,"EbolaForYou"
    ,"VagaBond"
    ,"LoneAssailant"
    ,"9mm"
    ,"SemiAutomatic"
    ,"SayHi2God"
    ,"SmashDtrash"
    ,"TheBully"
    ,"Sl4ught3r"
    ,"HappyPurging"
    ,"CantStopWontstop"
    ,"LocalGrimReaper"
    ,"Grave Digger"
    ,"BestServedCold"
    ,"HITnRUN"
    ,"TheKingIsDead"
    ,"BitchWhoDontMiss"
    ,"BigAssKiller"
    ,"OneShot"
    ,"SmokinAces"
    ,"DownInSmoke"
    ,"TheCursedOne"
    ,"SabotagingYou"
    ,"Rebel77"
    ,"TheManiac"
    ,"MyRage"
    ,"KeepBleeding"
    ,"K-9"
    ,"Valkyrie"
    ,"Slayer"
    ,"Satan"
    ,"Daredevil"
    ,"NightTerror"
    ,"Catch-22"
    ,"Mercenary"
    ,"X-hibit"
    ,"BlazeOfFury"
    ,"Venom"
    ,"Narcissus"
    ,"Vainglory"
    ,"Poison"
    ,"TigerClaw"
    ,"Excavator"
    ,"Yarder"
    ,"Trencher"
    ,"PowerTrain"
    ,"Dementor"
    ,"MercyLessSoul"
    ,"Wrecker"
    ,"Hell-Raiser"
    ,"KindaHomicidal"
    ,"IAMTHEREAPER"
    ,"Redviper101"
    ,"MurderSheWrote"
    ,"Bulletz4Breakfast"
    ,"IndominusRexxx"
    ,"UnderMeYourDead"
    ,"FlominateDominion"
    ,"SeekNDstroy"
    ,"SoulessImperator"
    ,"BaseKillerWolf"
    ,"ParanoiaSyndicate"
    ,"HarmonicDeath"
    ,"ShittinBullets69"
    ,"AlphaReturns"
    ,"X_BadBoy"
    ,"HeroOfBlackday"
    ,"Highlander Monk"
    ,"Impulsive Flower"
    ,"NemesisX"
    ,"SmashBuster"
    ,"SmashDtrash"
    ,"SpitFire"
    ,"NoTolerance"
    ,"RektalBead"
    ,"DarkLord"
    ,"Hitmany"
    ,"LastSamurai"
    ,"Joe_Mama"
    ,"Shaquille.oatmeal"
    ,"JuliusSneezer"
    ,"JuliusSeizure"
    ,"Bread Pitt"
    ,"panini_not_meanie"
    ,"EatingHawaiianPizza"
    ,"Granny4theWIN"
    ,"SargentSaltNPepa"
    ,"PookieChips"
    ,"LOWERCASE GUY"
    ,"DroolingOnU"
    ,"ihavethingstodo.jpg"
    ,"fartoolong"
    ,"PNUT"
    ,"MomsSpaghetti"
    ,"fatBatman"
    ,"iNeed2p"
    ,"LactoseTheIntolerant"
    ,"PookieChips"
    ,"FartinLutherKing"
    ,"Ariana_Grandes_Ponytail "
    ,"ElfishPresley"
    ,"WustacheMax"
    ,"peap0ds"
    ,"Not-Insync"
    ,"Milf_n_Cookies"
    ,"The Monalisa"
    ,"Married Man"
    ,"MaxicanChoncho"
    ,"Onion King"
    ,"Poptart AK47"
    ,"ScaryPumpkin"
    ,"SnowWhiteLuvr"
    ,"MasterThief"
    ,"InsufferableAttentionWhore"
    ,"FortOff"
    ,"Halochic"
    ,"Obamastolemyps4"
    ,"Osama_Been_Laggin"
    ,"DorkNite"
    ,"TooWeak"
    ,"BluffinWithMyMuffin"
    ,"Deleted User"
    ,"IfISuckItsMyDad"
    ,"TomCruisin"
    ,"Imakesandwiches"
    ,"Ilovdik69"
    ,"KitchenHo"
    ,"Ihate69"
    ,"Samureye"
    ,"Phuck Yuu"
    ,"Il Phuck Yuu"
    ,"Slagathor"
    ,"PeekaBooOsamaSeeU"
    ,"2OldForThis"
    ,"name_is_in_use"
    ,"what_does_this_button_do"
    ," GenZWarrior"
    ,"LackingToesAndTolerance"
    ," FastAndCurious"
    ,"anonymouse"
    ,"SelfishPresely"
    ,"Pikachew"
    ,"Billie_Eyelash"
    ,"Cardi_C"
    ,"itsBritneyB1tch"
    ,"Justin_Case"
    ," CaptainJackNarrow"
    ,"Jim_Doesnt_Carrey"
    ,"BearGrills"
    ,"MartinRouterKing"
    ,"suck_my_popsicle"
    ,"fartn_roses"
    ,"buzzed_lightyear"
    ,"Avo-Cardio"
    ,"Keep Calm and Curry On"
    ,"How I Met Your Melons"
    ,"Drop the Beet"
    ,"James_blond"
    ,"Tiny Wrestler"
    ,"AssAssSeen"
    ,"IPlayFarmHeroes"
    ,"Asleep"
    ,"QueenKong"
    ,"Gigantic_Wang"
    ,"Brosef_Stalin Game_over"
    ,"Chief-Choke-a-ho"
    ,"HandsomeBanana"
    ,"SmallPeePee"
    ,"hanging_with_my_gnomies."
    ,"hoosier-daddy."
    ,"OP_rah"
    ,"Something"
    ,"regina_phalange"
    ," FreddyMercurysCat"
    ,"hogwartsfailure"
    ,"peterparkerspuberty"
    ,"RootinTootinPutin"
    ,"IwasReloading"
    ,"fbi_surveillance_team"
    ,"TheDarkKing"
    ,"SoulKing"
    ,"TwoHands"
    ,"CopyNinja"
    ,"Kira"
    ,"StrawHat"
    ,"FireFistAce"
    ,"Chidori"
    ,"Takanome"
    ,"Akagamino"
    ,"FoxFire"
    ,"Lightning Emperor"
    ,"Heavenly Yasha"
    ,"FlowerSwordVista"
    ,"Charisma of Evil"
    ,"SurgeonOfDeath"
    ,"SnakePrincess"
    ,"KnightoftheSea"
    ,"White Demon"
    ,"BlackReaper"
    ,"MarcoThePheonix"
    ,"ComicMan"
    ,"The Black Swordsman"
    ,"Zero"
    ,"ThePalmtopTiger"
    ,"LittleRookie"
    ,"The Man With Seven Scar"
    ,"Battosai the Manslayer"
    ,"God’s Tongue"
    ,"The Flame Alchemist"
    ,"Caped Baldy"
    ,"Handsome_tooru"
    ,"Metalupa"
    ,"PotatoGirl"
    ,"Efreet"
    ,"RedKing"
    ,"Rhino Schneider"
    ,"the_eyes@blablabla.bla"
    ,"The Lightning Flash"
    ,"The General from Hell"
    ," The Red Comet"
    ,"EyePatch"
    ,"Uravity"
    ,"SogeKing"
    ,"Kirito"
    ,"Bohemian Knight"
    ,"WretchedEgg"
    ,"Demon of the Hidden Mist"
    ,"Hawkeye"
    ,"Menma"
    ,"PervySage"
    ,"TheCorruptKing"
    ,"HeroKiller"
    ,"OrangeHokage"
    ,"PirateHunter"
    ,"HikiGerma"
    ,"BlackLeg"
    ,"DevilChild"
    ,"CottonCandyLover"
    ,"GarpTheFist"
    ,"TheWhiteHunter"
    ,"TheRevolutionary"
    ,"GreenBeast"
    ,"TheLostUchiha"
    ,"SlugPrincess"
    ,"YellowFlash"
    ,"WhiteFang"
    ,"TheTaillesBeast"
    ,"TheFenceSitter"
    ,"Red Hot blooded Habanero"
    ,"IceBoy"
    ,"Grimmjow Lumberjack"
    ,"AfroDude"
    ,"TheFreakyScientist"
    ,"TheCatBurgler"
    ,"MurderMachine"
    ,"BlackLeg"
    ,"RedLeg"
    ,"TheWildfire"
    ,"ThePlague"
    ,".! (-_-).!."
    ,"|Re$pEcT|"
    ,"*S~@~M~u~R~@~I*"
    ,"-=Xom9k=-"
    ,"™Le[G]1on™|Killer|"
    ,"kill_m@sterS™| graf","eX™","^NoN STOP^","K*E*M*P*E*R","★S_U_P_E_R-N_E_O_N★","T_E_R_M_I_N_A_T_O_R","GL@moYr…♥…pR!ncEEs@","★TneEvilCheat★","[O] ska [R]","$ ST @ .LKER $","XyL [i] gaN4eG","{.: LSD: .Prizrak}",".::ExclusivE::.","3Jl0u*WhoJnuk","*** AWP — P R o F I ***","|.::Gr@nD_M@steR::.|","n1ce!™","—-PrOsTo ShArIcK—-","★彡[ᴅᴇᴀᴅ ᴋɪʟʟᴇʀ]彡★","✪FasTIK✪"
    };
        }
    }
}
